#! /bin/sh
#
# test-bad-argument
# Test running with invalid command-line flag
#
# Copyright (c) 2009, 2010 Free Software Foundation, Inc.
#
# Copying and distribution of this file, with or without
# modification, are permitted in any medium without royalty
# provided the copyright notice and this notice are preserved.

# srcdir and builddir are defined in the environment

# If TERM is not set to a terminal type, choose a default
if test -z "$TERM" -o "$TERM" = "unknown"; then
    TERM=vt100
    export TERM
fi

"$builddir/zile" --unknown-flag --load "$srcdir/quit.el"
